### ISSUE TITLE
cannot write test models

### ISSUE THREAD

**Issue by Karrenbelt** [opencobra/cobrapy#869] opened 2019-07-05 12:36 UTC
#### Problem description & Code Sample

libsbml error trying to set model history when attempting to write the test models to a file for 'textbook' and 'ecoli' model, fine for 'salmonella'

```
import cobra
import cobra.test
import platform

cobra.io.write_sbml_model(cobra.test.create_test_model('textbook'), 'textbook.xml')
```

#### Actual Output

Error encountered trying to <set model history>.
LibSBML error code -5: The object passed as an argument to the method is not of a type that is valid for the operation or kind of object involved. For example, handing an invalidly-constructed ASTNode to a method expecting an ASTNode will result in this error.

#### Dependency Information

platform.system()
'Darwin'

platform.python_version()
'3.6.6'

cobra.\_\_version\_\_
'0.15.3'

**Comment by Midnighter** [comment] 2019-07-05 15:06
Duplicate of #850. It is only an error message. It still works fine.

**Closed by Midnighter** 2019-07-05 15:06 UTC
