### ISSUE TITLE
Update cobra on anaconda repository

### ISSUE THREAD

**Issue by cossio** [opencobra/cobrapy#572] opened 2017-08-09 22:00 UTC
The latest version on the anaconda repository is 0.4,

https://anaconda.org/search?q=cobra

**Comment by hredestig** [comment] 2017-08-10 11:36
There was quite some discussion and effort on making cobra recipes but from what I understand it was not directly straight-forward and eventually it was decided to only deliver cobrapy via regular pypi. As there now are wheels for all major platforms, python versions, there shouldn't be any need to also host a package in anaconda repository. Do you have any strong reason to prefer anaconda over pypi or just pointing out the very old package? In the latter case I'd say we should just get cobrapy removed from there completely.

**Comment by cossio** [comment] 2017-08-10 11:46
I can use pypi, I just installed like that. Although conda would be more comfortable.
In the mean time maybe just remove the old cobrapy from conda, to avoid confusion.

**Comment by pstjohn** [comment] 2017-08-10 20:48
There's also this: conda-forge/staged-recipes#182
I would probably just use pypi

**Comment by hredestig** [comment] 2017-08-14 06:28
https://github.com/bioconda/bioconda-recipes/issues/5509

**Comment by hredestig** [comment] 2017-08-14 09:06
Bioconda keeps old packages for backwards compatibility/reproducibility so old version will not be removed. If anyone feels updating the bioconda package (and keeping up-to-date) they are most welcome to contribute but since no clear advantages over pypi has emerged I'm closing this.

**Closed by hredestig** 2017-08-14 09:06 UTC
