### ISSUE TITLE
Build issues on Debian also with verison 0.21.0

### ISSUE THREAD

**Issue by tillea** [opencobra/cobrapy#1036] opened 2021-02-07 08:15 UTC
#### Problem description
Thanks to the new release to fix issue #1030 .  I tried creating a Debian package of this new version 0.21.0 but it fails to pass its build time test as well.  
[Here is the complete build log.](https://github.com/opencobra/cobrapy/files/5938489/python-cobra_0.21.0-1_amd64.build.zip)
Kind regards, Andreas.

**Comment by cdiener** [comment] 2021-02-07 16:15
Like I commented on the previous issue. The current version of swiglpk unfortunately does not work with GLPK 5.0. The SBML errors are also caused by that. This has been fixed recently in the master branch of swiglpk so it should work if you rebuild swiglpk from that.

Unfortunately there is no swiglpk release that includes that fix yet because the CI is currently broken. So that will still take a little while...

**Comment by cdiener** [comment] 2021-03-20 20:19
Swiglpk has a new release now, so that should be fixed.

**Closed as completed by cdiener** 2021-03-20 20:19 UTC
