### ISSUE TITLE
Empty compartment list in the output model

### ISSUE THREAD

**Issue by silviamorins** [opencobra/cobrapy#729] opened 2018-06-22 10:14 UTC
After generating a model in COBRApy, I printed it in SBML format; however, this file is not valid because the list of compartments is empty, even though the compartment assignment worked just fine (every compound has a compartment assigned):

``` 
<listOfParameters>
<parameter constant="true" id="cobra_default_lb" sboTerm="SBO:0000626" units="mmol_per_gDW_per_hr" value="-1000"/>
<parameter constant="true" id="cobra_default_ub" sboTerm="SBO:0000626" units="mmol_per_gDW_per_hr" value="1000"/>
<parameter constant="true" id="cobra_0_bound" sboTerm="SBO:0000626" units="mmol_per_gDW_per_hr" value="0"/>
</listOfParameters>
<listOfCompartments/>
<listOfSpecies>
<species boundaryCondition="false" constant="false" hasOnlySubstanceUnits="false" id="M_glc__D_e" compartment="e" fbc:charge="0" fbc:chemicalFormula="C6H12O6"/>
<species boundaryCondition="false" constant="false" hasOnlySubstanceUnits="false" id="M_glc__D_p" compartment="p" fbc:charge="0" fbc:chemicalFormula="C6H12O6"/>
...
```

**Comment by taylo5jm** [comment] 2018-11-04 19:09
This seems to be working in version 0.13.4. 

I downloaded a model from BiGG. 
```
curl -O 'http://bigg.ucsd.edu/static/models/iMM904.xml.gz'
gunzip iMM904.xml.gz
```

Read the model, saved it with `write_sbml_model`, and inspected the model compartments. 

```
# coding: utf-8
import cobra
print(cobra.__version__)
model = cobra.io.read_sbml_model('iMM904.xml')
all([i.compartment in model.compartments.keys() for i in model.metabolites])
cobra.io.write_sbml_model(model, 'iMM904-out.xml')
from_file = cobra.io.read_sbml_model('iMM904-out.xml')
all([i.compartment in model.compartments.keys() for i in from_file.metabolites])
```

I pasted the SBML below.

```
...
   29    <listOfCompartments>
   30      <compartment constant="true" id="c" name="cytosol" />
   31      <compartment constant="true" id="m" name="mitochondria" />
   32      <compartment constant="true" id="e" name="extracellular space" />
   33      <compartment constant="true" id="x" name="peroxisome/glyoxysome" />
   34      <compartment constant="true" id="r" name="endoplasmic reticulum" />
   35      <compartment constant="true" id="v" name="vacuole" />
   36      <compartment constant="true" id="n" name="nucleus" />
   37      <compartment constant="true" id="g" name="golgi apparatus" />
   38    </listOfCompartments>
```

**Comment by matthiaskoenig** [comment] 2019-02-27 10:04
Closing this. Cannot reproduce and seems to be solved.
If this issue persists please reopen and provide a minimal cobrapy python code which shows the issue.
Without a code example which shows the issues this is impossible to debug.

**Closed by matthiaskoenig** 2019-02-27 10:04 UTC
Labels: SBML
