### ISSUE TITLE
How to acceess to couplingConstraints in Harvey Model wwith cobrapy please

### ISSUE THREAD

**Issue by Ilhem36** [opencobra/cobrapy#1251] opened 2022-07-14 10:42 UTC
#### Problem description

![image](https://user-images.githubusercontent.com/75625865/178964773-2fe09cf5-3c6b-41f3-8390-134ec0170cbc.png)

**Comment by cdiener** [comment] 2022-07-14 15:32
Duplicate of #1252. For Issues also please fill out all parts of the template. You can also use "Discussions" for questions.

**Closed as completed** 2022-07-14 15:32 UTC
