### ISSUE TITLE
Sampler validation does not pick up constraints from the model

### ISSUE THREAD

**Issue by Buiboni** [opencobra/cobrapy#1019] opened 2020-11-09 13:08 UTC
#### Problem description

Hi everyone,
I am working with the sampling module of Cobra and I came across an unexpected behavior. When using the `HRSampler.validate(self, samples))` method I think that the code is not taking the inequalities into account.
Here is the condition in the `validate(self, samples) `:
https://github.com/opencobra/cobrapy/blob/797951e2ac780093e5b8aff78192f1f182908410/src/cobra/sampling/hr_sampler.py#L524
The problem is that when I try to validate some flux samples I won't have the first condition `samples.shape[1] == len(self.model.variables)` but I still want the sample to respect the inequalities I have.

And in the next line:
https://github.com/opencobra/cobrapy/blob/797951e2ac780093e5b8aff78192f1f182908410/src/cobra/sampling/hr_sampler.py#L525-L534
I think there is an error of dimension as one needs to take the transpose of `prob.inequalities.dot(samples.T)` to be able to subtract  `prob.bounds[0,]`.

#### Code Sample

```python
import cobra
import cobra.test


model = cobra.test.create_test_model("textbook")
# Now same model with a constraint on the biomass flux
model_constr = cobra.test.create_test_model("textbook")
constr = model_constr.problem.Constraint(
    model_constr.reactions.Biomass_Ecoli_core.flux_expression, name="bio_cons",
    lb=0.2,
    ub=10)
model_constr.add_cons_vars(constr)
# Creation of the two samplers for the models
sampler = cobra.sampling.OptGPSampler(
        model, 
        thinning=10,
        processes=1)
sampler_constr = cobra.sampling.OptGPSampler(
        model_constr, 
        thinning=10,
        processes=1)

# Case with fluxes
batch = sampler.sample(10)
valide = sampler_constr.validate(batch)

# Case with variables
batch_var = sampler.sample(10,fluxes=False)
valide = sampler_constr.validate(batch_var)
```
The flux case wont give you any error but if you look at `batch['Biomass_Ecoli_core']` you can see values under 0.2.
The variable case will throw:

```
Traceback (most recent call last):

  File "/home/e19h357f/dev/FME/untitled0.py", line 37, in <module>
    valide = sampler_constr.validate(batch_var)

  File "/home/e19h357f/anaconda3/envs/cobra/lib/python3.8/site-packages/cobra/sampling/hr_sampler.py", line 503, in validate
    raise ValueError(

ValueError: Wrong number of columns. samples must have a column for each flux or variable defined in the model!
```

Whereas `len(model_constr.variables)` and `len(model.variables)`  are both equal to 190. By looking inside the sampler we have `len(self.model.variables)` equal to 191 though. The constraint has been transformed into a variable.

### Context

<details>

```
System Information
==================
OS                    Linux
OS-release 5.4.0-52-generic
Python                3.8.6

Package Versions
================
appdirs                                   1.4.4
cobra                                    0.20.0
depinfo                                   1.5.4
diskcache                                 5.0.3
future                                   0.18.2
httpx                                    0.16.0
importlib_resources                           ?
numpy                                    1.19.2
optlang                                   1.4.4
pandas                                    1.1.4
pip                                      20.2.4
pydantic                                  1.7.2
python-libsbml-experimental                   ?
rich                                      9.1.0
ruamel.yaml                             0.16.12
setuptools                  49.6.0.post20201009
six                                      1.15.0
swiglpk                                  4.65.1
wheel                                    0.35.1
```

</details>

**Comment by cdiener** [comment] 2020-11-09 18:07
I think the problem is that you assign an invalid bound. Biomass_Ecoli_core already has a variable bound that by default includes zero. Now you add an additional constraint that violates the variable constraint. The only reason it work is beacuse the sampler runs through the inequalities first and then the variables. In your case that overwrites the set constraint. If you do:

```Python
model_constr = cobra.test.create_test_model("textbook")
model_constr.reactions.Biomass_Ecoli_core.bounds = (0.2, 10)
```

it should work.

**Comment by Buiboni** [comment] 2020-11-09 22:19
Hi,
Thank you for your answer. Unfortunately this was just to show the issue. The problem does not lie in the fact that I did not use the model correctly for this kind of constraint (but one should be able to add constraints without changing bounds of the variables).
If you try the following constraint :
```python
constr = model_constr.problem.Constraint(
    model_constr.reactions.Biomass_Ecoli_core.flux_expression +
    model_constr.reactions.EX_co2_e.flux_expression, name="bio_cons",
    lb=0.2,
    ub=10)
```
it will be exactly the same. The batch of the sampler without constraint will give results with:
```
> batch.EX_co2_e
0    14.648416
1    15.886829
2    10.920718
3    34.574995
4    33.893776
5    30.247715
6    28.554663
7    31.489034
8    27.622522
9    24.913988
> batch.Biomass_Ecoli_core
0    0.016279
1    0.016481
2    0.016652
3    0.008543
4    0.018107
5    0.017525
6    0.014515
7    0.013047
8    0.012879
9    0.013352
> valide
array(['v', 'v', 'v', 'v', 'v', 'v', 'v', 'v', 'v', 'v'], dtype='<U3')
```

**Comment by cdiener** [comment] 2020-11-10 02:00
Hey, thanks for the update. I can reproduce that issue. Looks like the constraint_matrices code got broken. I'll investigate.

**Comment by cdiener** [comment] 2020-11-10 18:34
So the variables case works for me with the latest version of cobrapy:

```
In [46]:  
    ...: # Case with variables 
    ...: batch_var = sampler.sample(10,fluxes=False) 
    ...: valide = sampler_constr.validate(batch_var)                                                                                                                          

In [47]: valide                                                                                                                                                               
Out[47]: array(['u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u'], dtype='<U3')
```

The case with fluxes will be a bit tricky to fix. Constraints can be defined on only forward or reverse fluxes so not any constraint can be expressed in original fluxes. So you have to filter the constraints that are valid flux consraints first and only check those. Alternatively, we could transform the flux samples back to separate forward reverse samples and check those... I will try around what works best.

**Comment by cdiener** [comment] 2022-03-14 17:53
So I experimented a bit with that but there is no good solution. If you only ask for a reversible solution (one flux for each reaction) from the sampler there is no way of ensuring that all possible constraints are met. For instance if your flux is v = v_f - v_b and you have constraints v_f > 0 and v_b > 0 you may get a solution v = 1 and there is no way of telling whether the constraints are met since either `1 = v = -1 - (-2)` or `1 = v = 2 - 1` could apply. So the only way to ever check for all constrains is to use the `fluxes=False` arguments in the `Sampler.sample` method and validate those which already use all constraints. So closing this for now.

**Closed as completed by cdiener** 2022-03-14 17:53 UTC
