### ISSUE TITLE
errors in core model reaction annotations

### ISSUE THREAD

**Issue by Karrenbelt** [opencobra/cobrapy#889] opened 2019-08-02 16:47 UTC
maybe doesn't belong here, but not sure where else to go and I'm guessing the message will get through.

most reactions map as follows (id, BiGG annotation in the model):
R_ENO: ENO

but for the biomass reaction it maps as follows:
R_BIOMASS_Ecoli_core_w_GAM: Ecoli_core_w_GAM
I think the BIOMASS part needs to remain

for the exchange reactions (one example):
R_EX_ac_e: ac
which is strange since 'ac' is a BiGG metabolite identifier, not a reaction identifier

then there is one reaction with faulty rhea identifiers:
R_GLNabc: [29895#1, 29896#1, 29897#1, 29898#1]
as it appears, these should probably be  [29895, 29896, 29897, 29898]

**Comment by cdiener** [comment] 2019-08-02 18:02
Hey could you post a [reproducible example](https://stackoverflow.com/help/mcve) that illustrates the behavior. Exchange reactions are often named by the metabolite they import/export so that is common across many models. Annotations are mostly provided by the model itself and thus by the person that created it, but there may be parsing issues on our side...

**Comment by Karrenbelt** [comment] 2019-08-02 18:32
sorry I should have been more explicit, and probably posted this somewhere else, but I wasn't sure where. This has nothing to do with cobra. These are presumed errors in the E. coli core model sbml file, found here http://bigg.ucsd.edu/models/e_coli_core

**Comment by cdiener** [comment] 2019-08-02 19:28
Oh, okay. The BIGG Github repo is https://github.com/SBRG/bigg_models. Opening an issue there likely will get you a better reply.

**Comment by Midnighter** [comment] 2019-08-03 16:32
Closing this issue since https://github.com/SBRG/bigg_models/issues/344 is tracking this.

**Closed by Midnighter** 2019-08-03 16:32 UTC
Labels: SBML, needs information
