### ISSUE TITLE
remove_reactions() does not revert upon exiting context

### ISSUE THREAD

**Issue by yphillip** [opencobra/cobrapy#661] opened 2018-01-31 23:36 UTC
#### Problem description

I am trying to use remove_reactions() in a context, but it appears that after leaving the context, the removed reaction is still not present, even though it's accessible by model.reactions.X. In my example, I delete the biomass reaction within a context and as expected the model can't grow, but upon exiting the context, flux no longer goes through the biomass reaction.

#### Code Sample

Create a [minimal, complete, verifiable example
](https://stackoverflow.com/help/mcve).

```python
import cobra.test
model = cobra.test.create_test_model('ecoli')

print("Outside context (before): max biomass: ", model.slim_optimize(), " Number of reactions: ", len(model.reactions))

with model:
    print("context (before delete biomass): max biomass: ", model.slim_optimize(), " Number of reactions: ", len(model.reactions))
    
    model.remove_reactions(['Ec_biomass_iJO1366_core_53p95M'])
    
    print("context (after delete biomass): max biomass: ", model.slim_optimize(), " Number of reactions: ", len(model.reactions))

print("Outside context (after): max biomass: ", model.slim_optimize(), " Number of reactions: ", len(model.reactions))


```

#### Actual Output
Outside context (before): max biomass:  0.9823718127269693  Number of reactions:  2583
context (before delete biomass): max biomass:  0.9823718127269693  Number of reactions:  2583
context (after delete biomass): max biomass:  0.0  Number of reactions:  2582
Outside context (after): max biomass:  0.0  Number of reactions:  2583
#### Expected Output
Outside context (before): max biomass:  0.9823718127269693  Number of reactions:  2583
context (before delete biomass): max biomass:  0.9823718127269693  Number of reactions:  2583
context (after delete biomass): max biomass:  0.0  Number of reactions:  2582
Outside context (after): max biomass:  0.9823718127269693  Number of reactions:  2583
#### Output of `cobra.show_versions()`

<details>
# Paste the output of `import cobra;cobra.show_versions()` here.
System Information
==================
OS                           Linux
OS-release      4.4.0-43-Microsoft
Python                       3.6.3

Package Versions
================
pip                          9.0.1
setuptools     36.5.0.post20170921
cobra                       0.10.1
future                      0.16.0
swiglpk                      1.4.4
optlang                      1.3.0
ruamel.yaml                0.14.12
pandas                      0.22.0
numpy                       1.14.0
tabulate                     0.8.2
python-libsbml              5.16.0
lxml                         4.1.1
matplotlib                   2.1.2

</details>

**Comment by yphillip** [comment] 2018-02-01 00:06
As a workaround, model.reactions('Ec_biomass_iJO1366_core_53p95M').knock_out() produces the correct expected behavior (bounds reverted upon exiting context), so the issue still stands with remove_reactions()

**Comment by cdiener** [comment] 2018-02-01 02:29
Thanks for reporting. I suspect it's the same error as #655. A fix is currently under review and will be merged soon :)

**Comment by Midnighter** [comment] 2018-02-01 08:22
@yphillip if you want you can test whether current devel branch solves your problem. Otherwise wait until the next release. Either way please report back here in case the problem remains.

**Comment by yphillip** [comment] 2018-02-01 20:49
Thanks for taking a look into my issue.

I updated to the latest release: **print(cobra.__version__)** prints out **0.11.0**, and it looks like my issue is unfortunately still present. The output of my code sample is still the same as before, i.e. the last line is:

`Outside context (after): max biomass: 0.0 Number of reactions: 2583
`
But i expect:


`Outside context (after): max biomass: 0.9823718127269693 Number of reactions: 2583`

**Comment by Midnighter** [comment] 2018-02-01 21:45
I'll make a test case for it tomorrow and investigate.

**Comment by cdiener** [comment] 2018-02-02 01:13
I think the problem is that upon removing the biomass reaction the objective is set to empty (since the variable is gone) and that is not reverted by the context manager.

**Comment by pstjohn** [comment] 2018-02-02 18:56
ahh, good call. that shouldn't be too hard to fix.

**Comment by Midnighter** [comment] 2018-09-06 09:40
@pstjohn do you want to take a stab at this?

**Comment by pstjohn** [comment] 2018-09-06 16:09
yikes, forgot about this one. I think I've got a fix working, PR incoming

**Closed** 2018-09-06 16:56 UTC
Labels: bug
