### ISSUE TITLE
error when importing model with duplicate reactions

### ISSUE THREAD

**Issue by jtyurkovich** [opencobra/cobrapy#789] opened 2018-11-29 20:05 UTC
#### Problem description

I am attempting to import a model (*.mat file), but the model contains a duplicated reaction and therefore results in an error.

However, the model does not get loaded into cobrapy because of this error. I might be missing something simple or some other function to help me out, but it appears that I am therefore unable to fix this model in cobrapy (i.e., I have to go into MATLAB, remove the duplicate reaction, then go back to Python and import the model into cobrapy).

It seems like a better solution might instead be to throw a warning but to still import the model, allowing me to go in and fix the duplicated reaction?

Thanks!

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
model = cobra.io.load_matlab_model('model_with_duplicate_rxn.mat', variable_name='model')

```

#### Actual Output

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-f3e50a23657c> in <module>()
----> 1 model = cobra.io.load_matlab_model('model_with_duplicate_rxn.mat', variable_name='model')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cobra/io/mat.py in load_matlab_model(infile_path, variable_name, inf)
     80     if variable_name is not None:
     81         return from_mat_struct(data[variable_name], model_id=variable_name,
---> 82                                inf=inf)
     83     for possible_name in possible_names:
     84         try:

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cobra/io/mat.py in from_mat_struct(mat_struct, model_id, inf)
    253             pass
    254         new_reactions.append(new_reaction)
--> 255     model.add_reactions(new_reactions)
    256     set_objective(model, coefficients)
    257     coo = scipy_sparse.coo_matrix(m["S"][0, 0])

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cobra/core/model.py in add_reactions(self, reaction_list)
    534 
    535         # First check whether the reactions exist in the model.
--> 536         pruned = DictList(filter(existing_filter, reaction_list))
    537 
    538         context = get_context(self)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cobra/core/dictlist.py in __init__(self, *args)
     37                 self._dict = other._dict.copy()
     38             else:
---> 39                 self.extend(other)
     40 
     41     def has_id(self, id):

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cobra/core/dictlist.py in extend(self, iterable)
    197                 # twice in the list being added
    198                 raise ValueError("id '%s' at index %d is non-unique. "
--> 199                                  "Is it present twice?" % (str(the_id), i))
    200 
    201     def _extend_nocheck(self, iterable):

ValueError: id 'EX_cpd15302_c0' at index 635 is non-unique. Is it present twice?
```

#### Expected Output

A warning that informs me there may be duplicate reactions instead of an error. (I could therefore use cobrapy to edit the model and fix the duplicates.)

#### Dependency Information

<details>

System Information
==================
OS         Darwin
OS-release 17.7.0
Python      3.6.6

Package Versions
================
cobra        0.13.4
depinfo       1.4.0
future       0.16.0
numpy        1.15.2
optlang       1.4.3
pandas       0.23.4
pip            18.0
ruamel.yaml 0.15.66
setuptools   39.0.1
six          1.11.0
swiglpk       1.5.1
tabulate      0.8.2

</details>

**Comment by Midnighter** [comment] 2018-11-29 21:12
Hi @jtyurkovich,

Unfortunately, it's not quite so easy. The containers holding reactions and metabolites on the `cobra.Model` are like dictionaries. It is therefore impossible to have multiple reactions with the same identifier.

Now, maybe the parser could be made smarter in order to avoid such an issue but let me ask you about the model instead. There is no SBML version available? And if it's only in Matlab then surely someone must work with it in Matlab who could fix the identifiers?

I'm focusing on the model side because (a) duplicate identifiers in my opinion are an error and not a warning and (b) the Matlab interface is quite old and unless you felt like fixing something yourself I doubt anyone would pick up the work soon.

**Comment by jtyurkovich** [comment] 2018-11-29 21:57
Thanks for the quick reply, @Midnighter 

I was going to use cobrapy to quickly build a small model as an example but then quickly realized that I wouldn't even be able to make such a model in cobrapy because of the exact issues you mention (using dictionaries, etc.) -- so this issue is really only relevant to (erroneous and perhaps legacy) models built on other platforms. 

While I completely agree that this definitely is an error in the model, the fact that cobrapy throws an error just means that I am unable to fix the error using cobrapy. It occurred to me that since there are surely other models with errors, it might be worth at least allowing cobrapy to be used to fix these errors -- otherwise a prerequisite to using cobrapy is having an error-free model.

I already easily fixed the error in my model in MATLAB, but I was also wondering if perhaps there was something I was unaware of that could help with the issue without having to go back to MATLAB (i.e., some other way to get the model into cobrapy). But from your response, it appears there is no cobrapy solution to importing or editing erroneous models, so MATLAB will have to do for now.

Thanks again!

**Comment by Midnighter** [comment] 2018-11-29 22:22
> While I completely agree that this definitely is an error in the model, the fact that cobrapy throws an error just means that I am unable to fix the error using cobrapy. It occurred to me that since there are surely other models with errors, it might be worth at least allowing cobrapy to be used to fix these errors -- otherwise a prerequisite to using cobrapy is having an error-free model.

That is a good point. What I can immediately see as a potential solution is a `ModelBuilder` class that is maybe more forgiving than the actual `Model` class. However, implementing that is a fair amount of work and not being a model builder myself I see other issues in cobrapy that are more pressing to me. Hopefully, in a future not too far, far away we will have database supported web platforms for building models.

**Comment by ChristianLieven** [comment] 2019-03-21 09:47
If you have your model in SBML format it should be as simple as a find&replace operation in your favourite text editor.

**Comment by Midnighter** [comment] 2019-03-21 10:13
I'm closing this one for now. It's not likely that we'll have something helpful on the cobrapy side soon.

**Closed by Midnighter** 2019-03-21 10:13 UTC
Labels: help-wanted, user-request

**Comment by jtyurkovich** [comment] 2019-06-25 15:03
Another similar use-case to consider here: [this model was just published](https://www.frontiersin.org/articles/10.3389/fmicb.2019.01283/full) online today. There are 3 reactions for which `model.lb == model.ub` -- meaning that cobrapy yields the error `AssertionError: lower bound is greater than upper` when I try to load it in.

Because I can't load this SBML model into cobrapy at all, I am forced to load into MATLAB to fix these issues, then I can load into cobrapy and use the model. 

Would be nice if some of these types of things just returned a warning instead of an error, because otherwise invalid models just aren't compatible with cobrapy.

**Comment by cdiener** [comment] 2019-06-25 17:55
This last one seems to be a different issue and seems to be a parsing bug. Would you mind opening a new issue with a reproducible example?

**Comment by matthiaskoenig** [comment] 2019-06-26 07:14
Duplicate ids are a serious issue and should be fixed on the model building side. Most tools will have problems with them because they store things internally as a hashmap or map information on the ids.
If your ids would be isolated information this would be no issue, you would just do simple replace on the ids. But the ids are referenced within the model, so that ambiguity is introduced which can not be resolved by a parser. E.g. one has a group in which the reaction id reference is referenced. Which of the two reactions with identical ids is meant?

> If you have your model in SBML format it should be as simple as a find&replace operation in your favorite text editor. Just rename the offending reaction and sort out the rest once it loads in cobrapy.

Like mentioned above. You have to take care of fixing all the references in the model to the ids. If your reaction is not referenced by any other object the replace will work, otherwise you will break your model even more.

My opinion is a bit strict here. Model exchange standards exist to avoid such problems. If your model is clearly invalid you cannot expect tools to work with them without issues. One has to go back and fix the model. 
There is a big difference between a simulatable model and a knowledge-base or reconstruction in progress. The later two can often have missing information, actual problems like mass balance, duplicate reactions, .... . Consequently, tools focusing on reconstruction and model building should be much more tolerant than tools which have the primary focus of simulating and analysing models.
The reality is often more foggy and there is no clear separation between such tools, so it is often not easy to cut a clear line.
