### ISSUE TITLE
name 'cobra' is not defined

### ISSUE THREAD

**Issue by helenaherand** [opencobra/cobrapy#1137] opened 2021-11-27 12:14 UTC
Hi all,

I am using jupyter .ipynb and I am trying to import cobra without sys.path.append('/usr/local/lib/python3.9/site-packages'). Can anyone help me to solve this?

**Comment by cdiener** [comment] 2021-11-28 16:45
I think we need a bit more info here. How did you install Jupiter, wich OS are you using, how did you install cobrapy? Normally it should just work and you should not have to set `sys.path`.

**Comment by helenaherand** [comment] 2021-11-30 07:36
I have version Python 3.9.1 (`python3 -- version`), both in the terminal and in .ipynb. I installed the package with `pip3` but it seems that the package was installed in /usr/local/lib/python3.9/site-packages/ but the path in .ipynb is /Users/helher/opt/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages and I am using Jupyter. I solved it by `pip3 install --target=d:/Users/helher/opt/anaconda3/envs/my-rdkit-env/lib/python3.7/site-packages cobra` but I have never specified the path before and the solution is not ideal.

**Comment by cdiener** [comment] 2021-11-30 15:01
Okay I see. I think the issue is that you have a mix of conda and pip packages. It should be fixed if you install cobrapy with conda which should also fix your optlang issues. Open a terminal or conda shell (on Windows) and install cobrapy with `conda install -c conda-forge -c defaults cobra` .

**Comment by Midnighter** [comment] 2022-01-24 00:32
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.

**Closed as completed by Midnighter** 2022-01-24 00:32 UTC
