### ISSUE TITLE
OptGPSampler raises ValueError when additional constraints are added

### ISSUE THREAD

**Issue by RikvR** [opencobra/cobrapy#911] opened 2019-10-03 11:33 UTC
#### Problem description

When using a model with additional constraints added, the OptGPSampler raises a ValueError when constructing the center from the warmup points:

In `cobra.sampling.optgp.py` (line 172):
`ValueError: `data` must have the same shapeas the created array.`

This is likely due to the parent class copying and updating the model in preparation for the sampling, causing the number of variables to change.

#### Suggested fix
In `cobra.sampling.optgp.py` (line 172):
replace `len(model.variables)` with `len(self.model.variables)`

#### Code Sample

```python
import cobra
import cobra.test

cobra.test.create_test_model("textbook")
model = cobra.test.create_test_model("textbook")

expression = model.reactions.TPI.forward_variable
constraint = model.problem.Constraint(expression=expression, name="test", lb=0, ub=1)
model.add_cons_vars([constraint])

sampler = cobra.sampling.OptGPSampler(model)
sampler.sample(1)
```

<details>

System Information
==================
OS                     Linux
OS-release 4.15.0-64-generic
Python                 3.7.4

Package Versions
================
cobra                       0.16.0
depinfo                      1.5.1
future                      0.17.1
numpy                       1.17.2
optlang                      1.4.4
pandas                      0.25.1
pip                         19.2.3
python-libsbml-experimental 5.18.0
ruamel.yaml                 0.16.5
setuptools                  41.2.0
six                         1.12.0
swiglpk                     4.65.0
wheel                       0.33.6

</details>

**Comment by cdiener** [comment] 2019-10-16 17:16
So I definitely agree with the fix. I can send a PR with the suggested change. However, the pasted code works for me (no errors). Even if the model is copied this should not alter the number of variables. What solver are you using?

**Comment by RikvR** [comment] 2019-10-21 11:43
It seems that it only errors when using gurobi as a a solver - adding the update call does not fix it. Both GLPK and cplex seem to be fine.

**Comment by cdiener** [comment] 2019-10-21 17:56
Looks like `Model.copy()` is broken for Gurobi. Unfortunately I don't have access to Gurobi so I can't debug it further. If you would like to confirm the error you could run the following code:

```Python
from cobra.test import create_test_model

mod = create_test_model("textbook")
mod.solver = "gurobi"
print(len(mod.variables), len(mod.constraints))
print(len(mod.copy().variables), len(mod.copy().constraints))
```

If that does not print the same two numbers twice the bug is indeed in copying.

**Comment by gregmedlock** [comment] 2019-10-21 18:20
Just tested with the latest version of gurobi--the code in the OP works if the model is copied (e.g., `model = model.copy()`) prior to creating the sampler.

@cdiener your code led to the same number of variables/constraints for me, except if an additional constraint is added to the model. After the constraint is added, the number of constraints is updated immediately. When the model is copied, there is also one additional variable. The additional variable seems to be named "test_aux".

@RikvR could you confirm this works on your end? The sampler should construct and sample just fine with the reassignment to the copy, although I haven't figured out why yet. The first pair of print statements will be identical; the second should have an additional constraint in the original model and +1/+1 vars/constraints in the copy, then the last pair should have the same number of vars/constraints (but +1/+1 from the original).

```
import cobra
import cobra.test

cobra.test.create_test_model("textbook")
model = cobra.test.create_test_model("textbook")
print(len(mod.variables), len(mod.constraints))
print(len(mod.copy().variables), len(mod.copy().constraints))

expression = model.reactions.TPI.forward_variable
constraint = model.problem.Constraint(expression=expression, name="test", lb=0, ub=1)
model.add_cons_vars([constraint])
print(len(mod.variables), len(mod.constraints))
print(len(mod.copy().variables), len(mod.copy().constraints))

model = model.copy()
print(len(mod.variables), len(mod.constraints))
print(len(mod.copy().variables), len(mod.copy().constraints))

sampler = cobra.sampling.OptGPSampler(model)
sampler.sample(1)
```

**Comment by gregmedlock** [comment] 2019-10-21 19:01
Correct, the solver is set to gurobi. Will edit the above for mod/model use, it was just a quick copy/paste error

**Comment by cdiener** [comment] 2019-10-21 19:13
Great! And could you reproduce the original error with the code from the first post? The extra variable seems to be the problem. I think optlang creates some helper variables for constraints with Gurobi but those should be hidden which seems to break on copy. This should not be a huge issue and the proposed fix would probably still give correct results. I will report this upstream to optlang as well.

**Comment by gregmedlock** [comment] 2019-10-21 19:37
Yes, I reproduced the exact error from the OP.

**Comment by RikvR** [comment] 2019-10-22 10:10
@gregmedlock 

I can confirm that your example works as expected. The first pair is identical, the second pair has 0/+1 for the original, and +1/+1 for the copy. The final pair has the expected +1/+1 for both.

I think there could be an issue in Optlang with the way the Gurobi models are copied. The optlang Model is written to a temporary file in the .lp format, and parsed again to create a copy, but the round trip is not perfect. Also - I'm not sure where the original LP format clone is coming from? In cobrapy's model.copy, model._solver is copied / deepcopied, but I'm not sure where this get translated into a clone call on the Optlang model, or why this would use the lp format instead of the default json representation?
```python
import cobra
import cobra.test
import optlang

cobra.test.create_test_model("textbook")
model = cobra.test.create_test_model("textbook")
model.solver = 'gurobi'
expression = model.reactions.TPI.forward_variable
constraint = model.problem.Constraint(expression=expression, name="test", lb=0, ub=1)
model.add_cons_vars([constraint])

original = model._solver
lp_clone = optlang.Model.clone(model._solver, use_lp=True, use_json=False)
json_clone = optlang.Model.clone(model._solver, use_lp=False, use_json=True)
clone = optlang.Model.clone(model._solver, use_lp=False, use_json=False)
print(len(original.variables), len(original.constraints))  # (190, 73)
print(len(lp_clone.variables), len(lp_clone.constraints))  # (191, 73)
print(len(json_clone.variables), len(json_clone.constraints))  # (190, 73)
print(len(clone.variables), len(clone.constraints))  # (190, 73)
```

In addition - these variable and constraint numbers are the same for glpk or cplex - it seems to be more related to a limitation of the lp format or lp writer/parser of Optlang in general then just Gurobi. 
However, Gurobi seems to be the only solver that gets copied this way in cobrapy?

**Comment by cdiener** [comment] 2019-10-23 00:13
That was intentional since the optlang copy methods are usually much faster than cloning. Thanks for the amazing detective work! That really helps in pinning down the problem. Since it is an optlang problem we should report it there to get the serialization fixed for gurobi in optlang.

**Closed** 2019-10-26 12:09 UTC
