### ISSUE TITLE
As a user of cobrapy I want to rely on a correct, up-to-date, configurable SBML parser/writer

### ISSUE THREAD

**Issue by Midnighter** [opencobra/cobrapy#622] opened 2017-11-02 09:50 UTC

**Comment by ChristianLieven** [comment] 2018-01-21 20:37
I'd like to connect this feature request #653 with this epic.

**Comment by matthiaskoenig** [comment] 2018-03-23 11:17
This is a duplicate of #683 (will be implemented there)

**Comment by matthiaskoenig** [comment] 2018-03-23 13:39
Sorry, did not know about that.

**Comment by matthiaskoenig** [comment] 2019-03-18 09:17
Merged in develop.

**Closed by matthiaskoenig** 2019-03-18 09:17 UTC
Labels: SBML, duplicate
