### ISSUE TITLE
Silent drop of complex fbc:geneProductAssociation logic on SBML export

### ISSUE THREAD

**Issue by bdelepine** [opencobra/cobrapy#879] opened 2019-07-22 17:44 UTC
#### Problem description

Hello guys,

I was playing around with iJO1366 and COBRApy import/export features when I noticed that GPR having a mix of AND and OR logic are silently dropped on SBML export. I would have expected the logic to be exported without trouble as it is a valid SBML+fbc format.

HTH, best,

#### Code Sample

Taking [ACGAptspp as an example, you can see on BiGG](http://bigg.ucsd.edu/models/iJO1366/reactions/ACGAptspp) that its GPR is `(b2417 and b1101 and b2415 and b2416) or (b0679 and b2415 and b2416)`.

Now, if we import ACGAptspp from the iJO1366 shipped with COBRApy:

```python
import cobra
import cobra.test

model = cobra.test.create_test_model("ecoli")  # iJO1366
cobra.io.write_sbml_model(model, "cobra_iJO1366.xml")

print(model.reactions.ACGAptspp.gene_reaction_rule)
```

#### Actual Output

In Python, we do have `'( b2417 and b1101 and b2415 and b2416 ) or ( b0679 and b2415 and b2416 )'`.

In the SBML ("cobra_iJO1366.xml"), however:

```xml
      <reaction id="R_ACGAptspp" name="N-Acetyl-D-glucosamine transport via PEP:Pyr PTS  (periplasm)" reversible="false" fast="false" fbc:lowerFluxBound="cobra_0_bound" fbc:upperFluxBound="cobra_default_ub">
        <listOfReactants>
          <speciesReference species="M_pep_c" stoichiometry="1" constant="true"/>
          <speciesReference species="M_acgam_p" stoichiometry="1" constant="true"/>
        </listOfReactants>
        <listOfProducts>
          <speciesReference species="M_pyr_c" stoichiometry="1" constant="true"/>
          <speciesReference species="M_acgam6p_c" stoichiometry="1" constant="true"/>
        </listOfProducts>
      </reaction>
```

#### Expected Output

I would have expected something along:

```xml
      <reaction id="R_ACGAptspp" name="N-Acetyl-D-glucosamine transport via PEP:Pyr PTS  (periplasm)" reversible="false" fast="false" fbc:lowerFluxBound="cobra_0_bound" fbc:upperFluxBound="cobra_default_ub">
        <listOfReactants>
          <speciesReference species="M_pep_c" stoichiometry="1" constant="true"/>
          <speciesReference species="M_acgam_p" stoichiometry="1" constant="true"/>
        </listOfReactants>
        <listOfProducts>
          <speciesReference species="M_pyr_c" stoichiometry="1" constant="true"/>
          <speciesReference species="M_acgam6p_c" stoichiometry="1" constant="true"/>
        </listOfProducts>
        <fbc:geneProductAssociation xmlns:fbc="http://www.sbml.org/sbml/level3/version1/fbc/version2">
          <fbc:or sboTerm="SBO:0000174">
            <fbc:and sboTerm="SBO:0000173">
              <fbc:geneProductRef fbc:geneProduct="G_b2415" />
              <fbc:geneProductRef fbc:geneProduct="G_b2417" />
              <fbc:geneProductRef fbc:geneProduct="G_b1101" />
              <fbc:geneProductRef fbc:geneProduct="G_b2416" />
            </fbc:and>
            <fbc:and sboTerm="SBO:0000173">
              <fbc:geneProductRef fbc:geneProduct="G_b2415" />
              <fbc:geneProductRef fbc:geneProduct="G_b0679" />
              <fbc:geneProductRef fbc:geneProduct="G_b2416" />
            </fbc:and>
          </fbc:or>
        </fbc:geneProductAssociation>
      </reaction>
```

#### Dependency Information

<details>

System Information
==================
OS                              Linux
OS-release 3.10.0-957.21.3.el7.x86_64
Python                          3.6.8

Package Versions
================
cobra                        0.15.3
depinfo                       1.3.0
future                       0.16.0
numpy                        1.15.4
optlang                       1.4.3
pandas                       0.23.4
pip                          19.1.1
python-libsbml-experimental  5.18.0
ruamel.yaml                 0.15.81
setuptools                   41.0.1
six                          1.11.0
swiglpk                       1.4.4
tabulate                      0.8.2
wheel                        0.33.4

</details>

**Comment by bdelepine** [comment] 2019-07-22 17:58
Actually, this might be worse than that since other parts of the file are missing.

```python
import cobra
import cobra.test

model_test = cobra.test.create_test_model("ecoli")  # iJO1366
cobra.io.write_sbml_model(model_test, "cobra_iJO1366.xml")
cobra.io.read_sbml_model("cobra_iJO1366.xml")
```

I get the #850 error and then a traceback:

```
cobra.io.sbml.CobraSBMLError: Required attribute 'id' cannot be found or parsed in '<Species "L-Seryl-tRNA(Sec)">' with name 'L-Seryl-tRNA(Sec)'
```

And when I check the SBML, surprisingly enough, this is true, the 'id' attribute disappeared:
```xml
      <species id="M_sertrna_c" name="L-Seryl-tRNA(Ser)" compartment="c" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false" fbc:charge="1" fbc:chemicalFormula="C3H6NO2R"/>
      <species name="L-Seryl-tRNA(Sec)" compartment="c" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false" fbc:charge="1" fbc:chemicalFormula="C3H6NO2R"/>
      <species id="M_sheme_c" name="Siroheme" compartment="c" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false" fbc:charge="-8" fbc:chemicalFormula="C42H36FeN4O16"/>
```

I'm not sure the two problems are related. I think this depends on the model; I was able to read/write other models without that much troubles earlier today. My configuration might be an issue since I'm using somehow `python-libsbml-experimental 5.18.0`.

**Comment by matthiaskoenig** [comment] 2019-07-23 11:11
Hi @bdelepine,
I will have a look at this in the next few hours.

I am pretty sure the problem is due to invalid ids in the original model (i.e. the model is not a valid SBML model because the ids are not valid ids). Consequently, the ids cannot be written out and information associated with the respective objects cannot be stored in SBML.

I will add an error on SBML export which will tell you which ids cannot be serialized. It would be unfortunate if the example model has incorrect ids, but can say more after looking into the issue.

Best Matthias

**Comment by matthiaskoenig** [comment] 2019-07-23 14:17
I just checked your example and I get the following error message when trying to write the SBML file, which is exactly stating what is wrong with the model in respect to the ids:
```
import cobra
import cobra.test
model = cobra.test.create_test_model("ecoli")  # iJO1366
cobra.io.write_sbml_model(model, "cobra_iJO1366.xml")

```
results in
```
ERROR:root:'M_sertrna[sec]_c' is not a valid SBML 'SId'.
```
The id is not written because the id is not valid.

You cannot read the model again, because it is invalid due to missing ids, i.e.,
```
model2 = cobra.io.read_sbml_model("cobra_iJO1366.xml")
```
results in 
```
Traceback (most recent call last):
  File "/home/mkoenig/git/cobrapy/cobra/io/sbml.py", line 213, in read_sbml_model
    **kwargs)
  File "/home/mkoenig/git/cobrapy/cobra/io/sbml.py", line 384, in _sbml_to_model
    sid = _check_required(specie, specie.getIdAttribute(), "id")
  File "/home/mkoenig/git/cobrapy/cobra/io/sbml.py", line 1193, in _check_required
    raise CobraSBMLError(msg)
cobra.io.sbml.CobraSBMLError: Required attribute 'id' cannot be found or parsed in '<Species "L-Seryl-tRNA(Sec)">'. with name 'L-Seryl-tRNA(Sec)'
ERROR:cobra.io.sbml:None
```
The problem is that the model in the cobrapy test code was not valid SBML :/. The underlying bug has been fixed in the Bigg Models
https://github.com/SBRG/bigg_models/issues/55
but the updated SBML never made it in the cobrapy test code.

I just updated the test model in https://github.com/opencobra/cobrapy/commit/9a4b0fc5a7804d2a253a6eb85038e482224e05c8 and the id issue is fixed with this.

In addition I could reproduce the GPR issue and will provide a bugfix as soon as I have found the underlying cause.

**Comment by matthiaskoenig** [comment] 2019-07-23 16:33
This is now fixed in the `sbml-bugfixes` branch. Thanks a lot for reporting this.
Proper tests were added to avoid regression in the future.

Best Matthias

**Closed** 2019-07-24 07:42 UTC
Labels: SBML, bug

**Comment by bdelepine** [comment] 2019-07-24 08:22
Thank you for fixing this! It works like a charm.
