### ISSUE TITLE
Metabolic sampling

### ISSUE THREAD

**Issue by pipemg** [opencobra/cobrapy#516] opened 2017-05-23 14:40 UTC
I tried both with OptGPSampler and sampling, in both cases show something like this

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/[usr]/.local/lib/python3.5/site-packages/cobra/flux_analysis/sampling.py", line 644, in sample
    chunksize=1)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

**Comment by cdiener** [comment] 2017-05-23 15:57
After some probing I found that the problem is that the matrices in `sampler.problem` can get really big for large models. In this case they are about 6 GB in total which exceeds the maximum size multiprocessing can transfer across processes (size is encoded by a 32-bit int, so about 2.1 GB). There are 3 strategies to solve this:

1. use scipy sparse matrices which should reduce the size
2. use shared memory for the matrices (still big but don't need to be transferred)
3. rewrite the parallel parts in Cython (will require compilation)

**Closed** 2017-06-19 06:57 UTC
Labels: ready
