### ISSUE TITLE
Optimization error

### ISSUE THREAD

**Issue by caonetto** [opencobra/cobrapy#691] opened 2018-04-13 03:46 UTC
Hi, I am trying to run model.optimize in multiple models form which I have deleted certain genes and I keep on getting the following error. Any ideas? I am new to cobrapy and any help would be greatly appreciated.

Input

```
for m in models:
    model = cPickle.load(open(m))
    model.optimize()
    if model.solution.f < 0.00001:
        print "gap filling"
        sol = growMatch(model, dm_rxns=0, ex_rxns=1,iterations=1)
        for rxn in sol[0]:
            rxn = rxn.id.replace('_reverse', '')
            model.reactions[model.reactions.index(rxn)].lower_bound = -1

gaps = cPickle.load(open('gap_fill.pickle','r'))
gaps = gaps.fillna(0)
```

And this is the error I get.

```
OptimizationError                         Traceback (most recent call last)
<ipython-input-138-b541e654c9f9> in <module>()
      1 for m in models:
      2     model = cPickle.load(open(m))
----> 3     model.optimize()
      4     if model.solution.f < 0.00001:
      5         print "gap filling"

/home/users/conetto/.conda/envs/snakes/lib/python2.7/site-packages/cobra/core/model.pyc in optimize(self, objective_sense, raise_error)
    836                 objective_sense, original_direction)
    837         self.slim_optimize()
--> 838         solution = get_solution(self, raise_error=raise_error)
    839         self.objective.direction = original_direction
    840         return solution

/home/users/conetto/.conda/envs/snakes/lib/python2.7/site-packages/cobra/core/solution.pyc in get_solution(model, reactions, metabolites, raise_error)
    286     legacy solvers.
    287     """
--> 288     check_solver_status(model.solver.status, raise_error=raise_error)
    289     if reactions is None:
    290         reactions = model.reactions

/home/users/conetto/.conda/envs/snakes/lib/python2.7/site-packages/cobra/util/solver.pyc in check_solver_status(status, raise_error)
    406             "model was not optimized yet or solver context switched")
    407     else:
--> 408         raise OptimizationError("solver status is '{}'".format(status))
    409 
    410 

OptimizationError: solver status is 'aborted
```

Thanks for your help.

**Comment by gregmedlock** [comment] 2018-04-16 23:26
Are you able to share any of the models that give this error? A reproducible example might be needed to track down the issue.

Also, do you have access to the models prior to pickling? Would be helpful to know whether the error is dependent on pickling.

**Comment by caonetto** [comment] 2018-04-17 23:46
Thanks for your reply, by some reason this problems was associated to the conda install, which I think is a  problem with the solver. I had to install it through pip to make it work. 
However I am wondering, if the model cannot be optimised is there a way to configure it so that I can still get an answer from model.optimize() ?

Thanks for your help.

Cris.

**Comment by cdiener** [comment] 2018-04-18 19:18
So `model.optimize` has a `raise_error` argument for that. However, that one currently only works for Infeasible where you will still get a solution. For other states such as `numeric`, `suboptimal`, etc. you will have to trick cobrapy a bit (something I would like to change). For instance you can get the primal values from `model.solver.primal_values` if there are any...

Could you point me to the Anaconda package you installed (that didn't work) so we can contact the author (this one is not from us I think)?

**Comment by Midnighter** [comment] 2018-09-06 09:30
@cdiener is this something we'd still like to pick up or by chance is already possible?

**Comment by cdiener** [comment] 2018-09-06 15:52
Not possible yet. I can look into the solution status issue. For the Anaconda package I dunno. Maybe might be good to have an official package that is actually maintained but somebody would have to step up for that...

**Comment by Midnighter** [comment] 2018-09-06 16:40
I think the Anaconda problem has come up often enough to at least take a look. I'll do that.

**Comment by cdiener** [comment] 2018-09-14 16:43
I realized that we previously merged the alternative solver states so that is working already. For the aborted state that is usually a solver state that does not allow getting primals so we can not return that one. I have had problems in the past with Gurobi returning aborted states in the first iteration but that would be a bug in their Python lib...

**Comment by Midnighter** [comment] 2018-10-04 18:09
I'm closing this for now. Feel free to open it again if the problem is still relevant.

**Closed by Midnighter** 2018-10-04 18:09 UTC
Labels: enhancement

**Comment by Rakshith-Manandi** [comment] 2019-06-09 20:28
I'm trying to load an SBML model and I get the following error:

OptimizationError: solver status is 'unbounded' 

Any idea on how to solve this?

**Comment by cdiener** [comment] 2019-06-09 22:37
This error is unrelated to the previous thread but means that your model has no bounds set and the maximum growth rate would be infinity. You will need to set bounds on at least your import reactions to get something that can be optimized. Feel free to open a new issue or use Gitter in case you continue having problems.
