### ISSUE TITLE
Changing metabolite ID cause error in subsequent operation involving that metabolite

### ISSUE THREAD

**Issue by hvdinh16** [opencobra/cobrapy#832] opened 2019-04-11 17:36 UTC
To clarify, if I load the model, then change the ID of a metabolite X from 'old_id' to 'new_id'. When I subsequently change the reaction equation that associated with metabolite X, I would get an error. In addition, when I attempt to remove metabolite X from the model, I would also get an error. This does not happen if I save and reload the model when there are ID-change operations.

Please see the attachment for the scripts that I use where errors are found.
[metid_change_error.ipynb.zip](https://github.com/opencobra/cobrapy/files/3069886/metid_change_error.ipynb.zip)

**Comment by cdiener** [comment] 2019-04-11 18:12
Didi you use Gurobi by any chance (default if installed)? In that case this would be a duplicate of #819. Could you try to set the solver to GLPK with `model.solver = "glpk"` and see if that fixes your issue?

**Comment by hvdinh16** [comment] 2019-04-11 18:53
Thank you. That does fix the issue.

**Comment by cdiener** [comment] 2019-04-11 20:19
Closing as duplicate of #819.

**Closed by cdiener** 2019-04-11 20:19 UTC
