### ISSUE TITLE
Numpy 1.24 breaks builtin type aliases

### ISSUE THREAD

**Issue by marvinvanaalst** [opencobra/cobrapy#1305] opened 2022-12-19 13:11 UTC
#### Problem description

The numpy people marked aliases of builtin types like `np.bool` or `np.float` as deprecated in version [1.20.0](https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated). They are effectively deprecated with version [1.24.0](https://numpy.org/devdocs/release/1.24.0-notes.html#expired-deprecations) which was just released.

This leads to a bunch of `AttributeError`s, like 

```python
AttributeError: module 'numpy' has no attribute 'float'
```

Your `setup.cfg` states compatability for `numpy ~=1.13` which includes all minor versions >= 13 and thus causes CI to crash on this (but that's on the numpy folks).

I've started fixing this in [my fork](https://github.com/opencobra/cobrapy/compare/devel...marvinvanaalst:cobrapy:fix-numpy-builtin-aliases) but noticed during the tests that some of the dependencies like osqp have the same issue.

The best short-term fix is probably to exclude numpy versions `>=1.24` until all the dependencies have caught up on this.

**Comment by cdiener** [comment] 2022-12-20 15:07
Yes that makes sense. Feel free to send in a PR that pins numpy to a lower version in the setup.cfg.

**Comment by woutervh** [comment] 2023-01-31 19:23
> Feel free to send in a PR that pins numpy to a lower version in the setup.cfg.
This is the wrong solution. It hides the problem of using deprecated numpy-calls, 
The title wrongly suggests that numpy needs to fix an issue,

Pinning numpy to a lower-version only makes sense when the problem arises in the thirdparty package you cannot control.

in this case  the problem is only a single np.float in 
https://github.com/opencobra/cobrapy/blob/devel/src/cobra/io/dict.py#L71

**Comment by Midnighter** [comment] 2023-01-31 19:45
PR welcome 😉

**Comment by marvinvanaalst** [comment] 2023-02-01 08:53
> > Feel free to send in a PR that pins numpy to a lower version in the setup.cfg.
> > This is the wrong solution. It hides the problem of using deprecated numpy-calls,
> > The title wrongly suggests that numpy needs to fix an issue,
> 
> Pinning numpy to a lower-version only makes sense when the problem arises in the thirdparty package you cannot control.
> 
> in this case the problem is only a single np.float in https://github.com/opencobra/cobrapy/blob/devel/src/cobra/io/dict.py#L71

This problem is not confined to cobrapy, but also occurs for example in osqp, see [this issue](https://github.com/osqp/osqp-python/issues/104), which is a dependency of cobrapy. Since the [corresponding PR](https://github.com/osqp/osqp-python/pull/105) has not been merged yet, I don't see a better solution at this point in time


> PR welcome :wink:

The PR is [here](https://github.com/osqp/osqp-python/pull/105) :slightly_smiling_face:

**Comment by Midnighter** [comment] 2023-02-02 00:19
Ah, great. I'm not involved in the OSQP project so I can't help it along unfortunately.

**Comment by cdiener** [comment] 2023-02-02 01:11
It usually takes a while, but the OSQP folks have always come through in the past.

**Comment by cdiener** [comment] 2023-04-24 18:39
This has now been fixed in `osqp==0.6.2.post9` and `cobrapy==0.26.3`. I will remove the numpy pin for the next release.

**Closed as completed** 2023-04-24 18:39 UTC
