### ISSUE TITLE
cplex based optimization become slower with repeated model simulation

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/cobrapy#483] opened 2017-04-07 06:56 UTC
Hi all,

When running repeated simulations (pfba) with a model cplex based optimization becomes slower with every executed simulation. The increase in simulation time is almost linear, whereas glpk execution time stays constant over repeats.
I noticed this during running dynamic FBA where cplex performs worse and worse over time.
See figure, benchmarks and benchmark code attached.

![solver_timings](https://cloud.githubusercontent.com/assets/900538/24788817/d79fb802-1b6f-11e7-90a1-5423b0cb2c77.png)
[lp_benchmark.zip](https://github.com/opencobra/cobrapy/files/904737/lp_benchmark.zip)

```
from __future__ import print_function, absolute_import, division
import cobra
import optlang
import numpy as np
import timeit
from matplotlib import pyplot as plt
from six import iteritems


def benchmark(model, lp_solver, n_repeat=10, **kwargs):
    """ Benchmark the simulate function with provided simulation parameters.

    See simulate arguments for available kwargs.

    :return: numpy array of times
    """
    # set the solver
    model.solver = lp_solver
    print(model.solver.interface)

    timings = np.zeros(shape=(n_repeat, 1))

    for k in range(n_repeat):
        t_start = timeit.default_timer()
        simulate(model=model, lp_solver=lp_solver, **kwargs)
        timings[k] = timeit.default_timer() - t_start
        print('\t[{}/{}] {:2.3}'.format(k, n_repeat, timings[k,0]))

    print('-' * 40)
    print('N={}, mean+-SD'.format(n_repeat))
    print('\t{:.5f} +- {:.5f}'.format(np.mean(timings), np.std(timings)))
    print('-' * 40)
    return timings


def simulate(model, lp_solver, n_bounds=100):

    # step wise shut down of glucose
    glc_bounds = np.linspace(-10, -0.5, n_bounds)
    for lb_glc in glc_bounds:
        # set the lower bound (uptake direction) of the exchange reaction
        model.reactions.get_by_id("EX_glc__D_e").lower_bound = lb_glc
        # pfba
        cobra.flux_analysis.pfba(model)

if __name__ == "__main__":
    print('optlang:', optlang.__version__)
    print('cobra:', cobra.__version__)

    # run timings
    timings = {}
    for solver in ['glpk', 'cplex']:
        sbml_path = "ecoli_fba.xml"
        model = cobra.io.read_sbml_model(sbml_path)
        t_solver = benchmark(model=model, lp_solver=solver, n_repeat=30)
        timings[solver] = t_solver

    # plot results
    fig, ax1 = plt.subplots(nrows=1, ncols=1, figsize=(7, 7))

    for key, times in iteritems(timings):
        ax1.plot(times, '-s', linewidth=2, label=key)


    ax1.set_xlabel("repeat")
    ax1.set_ylabel("duration [s]")
    ax1.set_title("Timing of solver (repeated simulation)")
    ax1.legend()

    fig.savefig('solver_timings.png')
```

**Comment by matthiaskoenig** [comment] 2017-04-07 06:58
Forget the console output:
```
/usr/bin/python2.7 /home/mkoenig/git/sbmlutils/oven/lp_benchmark/lp_benchmark.py
optlang: 1.1.4
cobra: 0.6.0a4
<module 'optlang.glpk_interface' from '/usr/local/lib/python2.7/dist-packages/optlang/glpk_interface.pyc'>
	[0/30] 1.14
	[1/30] 1.13
	[2/30] 1.13
	[3/30] 1.13
	[4/30] 1.13
	[5/30] 1.13
	[6/30] 1.13
	[7/30] 1.13
	[8/30] 1.13
	[9/30] 1.13
	[10/30] 1.14
	[11/30] 1.17
	[12/30] 1.13
	[13/30] 1.13
	[14/30] 1.13
	[15/30] 1.13
	[16/30] 1.13
	[17/30] 1.13
	[18/30] 1.13
	[19/30] 1.13
	[20/30] 1.13
	[21/30] 1.13
	[22/30] 1.13
	[23/30] 1.13
	[24/30] 1.17
	[25/30] 1.13
	[26/30] 1.13
	[27/30] 1.13
	[28/30] 1.13
	[29/30] 1.13
----------------------------------------
N=30, mean+-SD
	1.13273 +- 0.00946
----------------------------------------
<module 'optlang.cplex_interface' from '/usr/local/lib/python2.7/dist-packages/optlang/cplex_interface.pyc'>
	[0/30] 1.65
	[1/30] 1.63
	[2/30] 1.64
	[3/30] 1.66
	[4/30] 1.67
	[5/30] 1.69
	[6/30] 1.7
	[7/30] 1.75
	[8/30] 1.73
	[9/30] 1.75
	[10/30] 1.76
	[11/30] 1.8
	[12/30] 1.78
	[13/30] 1.93
	[14/30] 2.15
	[15/30] 2.15
	[16/30] 2.19
	[17/30] 2.23
	[18/30] 2.27
	[19/30] 2.31
	[20/30] 2.34
	[21/30] 2.31
	[22/30] 2.43
	[23/30] 2.47
	[24/30] 2.52
	[25/30] 2.56
	[26/30] 2.6
	[27/30] 2.65
	[28/30] 2.6
	[29/30] 2.63
----------------------------------------
N=30, mean+-SD
	2.08571 +- 0.36351
----------------------------------------
```

**Comment by Midnighter** [comment] 2017-04-07 07:30
@matthiaskoenig thank you for the detailed report.

@KristianJensen does this look familiar to you? Since we use the optlang interfaces in the exact same way this seems like something to tackle in optlang?

**Comment by matthiaskoenig** [comment] 2017-04-07 07:44
Also why is cplex so slow? 
I would expect the commercial solvers to outperform glpk. In most benchmark results I saw cplex (and gurobi) are faster than glpk. Is the optlang interface slowing things down for cplex?

Are there some cobrapy (optlang) benchmarks comparing different solvers? If possible comparing to the raw optimization time.

I always saw the commercial solutions outperform GLPK
(2012) http://www.statistik.tuwien.ac.at/forschung/CS/CS-2012-1complete.pdf
http://www.gurobi.com/pdfs/benchmarks.pdf

**Comment by matthiaskoenig** [comment] 2017-04-07 08:15
Just out of curiosity I also tested gurobi. This does not show the linear increase in run time.
![solver_timings](https://cloud.githubusercontent.com/assets/900538/24791306/ec8307c4-1b79-11e7-8860-fd518f51ca7f.png)

**Comment by KristianJensen** [comment] 2017-04-07 08:30
That looks very odd indeed. I'll try to investigate. Does the time increase indefinitely if you let it run for n>30?

**Comment by KristianJensen** [comment] 2017-04-07 08:36
I've done some testing using your script. I'm using cameo (pre cobra 0.6) instead of cobra. With this setup I can't replicate the issue (python 3.4, optlang 1.1.4, cplex 12.6.1). I tried both with the model you provided and with iJO1366 from bigg.

It could be an issue with cplex 12.7.1. I'll give that a try as well.

**Comment by matthiaskoenig** [comment] 2017-04-07 09:30
Yes, runs to infinity ;)
The more simulations, the slower it gets.

**Comment by KristianJensen** [comment] 2017-04-07 14:17
I found the source of the problem. Until I can push a change in optlang you can fix it by calling `model.solver.problem.set_results_stream(None)` on a cplex model.

**Comment by cdiener** [comment] 2017-04-07 16:12
To comment on the speed differences between the solvers. cplex and gurobi are faster for the first solver but are much less efficient in recycling a previous solution basis. GLPK is much better in that regard.

**Comment by matthiaskoenig** [comment] 2017-04-07 16:48
@cdiener
Very interesting. Is this an inherent problem of cplex & gurobi, or due to how optlang is working with the solvers. I.e. would it possible to update some optlang code to make cplex&gurobi better at reusing the previous solution base?

**Comment by cdiener** [comment] 2017-04-07 17:00
@matthiaskoenig Inherent to cplex and gurobi. Basis reuse is only really efficient for primal simplex methods which is what glpk uses. clpex and gurobi use a lot of heuristics to make solving the model faster but reusing a basis is less straight forward there. They also pick their solver strategies themselves. If they happen to pick dual simplex or interior point methods there is no basis recycling at all. I guess the smaller code base of glpk also helps somewhat.

**Comment by hredestig** [comment] 2017-05-15 09:02
@KristianJensen did you implement a fix for this?

**Comment by KristianJensen** [comment] 2017-05-15 09:47
Yes, latest release of optlang should have fixed this

**Comment by hredestig** [comment] 2017-05-15 12:46
confirmed, thanks!

**Closed by hredestig** 2017-05-15 12:46 UTC
