### ISSUE TITLE
Reaction.remove_from_model does not trigger update in ArrayBasedModel

### ISSUE THREAD

**Issue by aebrahim** [opencobra/cobrapy#160] opened 2015-04-28 01:47 UTC
Example code to reproduce the issue

``` python
import cobra.test
m = cobra.test.create_test_model().to_array_based_model()
m.reactions[0].remove_from_model()
print(len(m.reactions))
print(m.S.shape[1])
```

The values should be identical.

Using m.remove_reactions([m.reactions[0]) works, however.

**Comment by vivekiitkgp** [comment] 2016-02-10 17:25
@aebrahim Should it? I am just trying to understand the intended behaviour.

`m.remove_reactions()` assumes a default action of updating the `S` matrix (`m` is `ArrayBasedModel`). However, `remove_from_model()`, `delete()` or `remove_reactions()` from `Reaction` and `Model` classes do not do anything about such matrix.

We can check if a matrix exists and can make update accordingly. And also include additional argument. But I'm not sure about the latter.

**Comment by vivekiitkgp** [comment] 2016-03-06 18:32
@aebrahim Ping.

**Comment by aebrahim** [comment] 2016-03-06 20:32
Sorry, I missed this last time.

I honestly don't know the best way to do this, which is why it's still open.

Perhaps
```if hasattr(model, "update"):
    model.upate()```

should be considered too

**Comment by vivekiitkgp** [comment] 2016-03-06 21:13
Hmm. I will give it a thought and post here again. Thanks for the suggestion.

**Comment by hredestig** [comment] 2017-01-10 09:30
closing this as we aim to deprecate the ArrayBasedModel

**Closed by hredestig** 2017-01-10 09:30 UTC
